### ISSUE TITLE
Cannot GET /users

### ISSUE THREAD

**Issue by TLKG** [jsa2/azureFNcustomHandlers#1]
Hello jsa2,
How are you? Found your [article ](https://securecloud.blog/2021/01/04/express-js-middlewares-on-azure-functions-via-custom-handlers/) for clues on how to convert/migrate existing Express middleware to AZF. Very helpful.
Interesting thing, using VSC/Windows, when I run this project locally F5 or `func host start --javascript`, `http://localhost:7071/users` got 

![image](https://user-images.githubusercontent.com/22269729/147797853-0d8d9aa2-7f18-494b-a21b-30ae771ef4c2.png)

Am I testing it right? Thank you and appreciate any feedback!

**Comment by jsa2** [comment]
Hi and thx for noting!, I had only added the index and proxy handler to app.js - I've now added the user handler (router) there. I previously tested this only in Linux, but confirmed, that also Windows should work 

**Linux:**
![image](https://user-images.githubusercontent.com/58001986/147811169-501443c4-e78b-4f7a-b022-812acc877b25.png)

**Windows**
![image](https://user-images.githubusercontent.com/58001986/147811251-87f3bf99-faaa-4163-9ca9-26e7a00d7d31.png)

**Comment by jsa2** [comment]
Updated the app.js

**Comment by TLKG** [comment]
Happy New Year and thanks for addressing it! 
Share some test findings. It works with this:
![image](https://user-images.githubusercontent.com/22269729/147834748-4fb59755-96fd-4ca5-88df-78e4bbfb6da6.png)

Googled found
An HTTP **304** not modified status code means that the website you're requesting hasn't been updated since the last time you accessed it. Typically, your browser will save (or cache) web pages so it doesn't have to repeatedly download the same information. This is an attempt to speed up page delivery. However, if this happens to your site, visitors could be prevented from accessing your web pages.

Though it brought some confusion should be ok for testing purpose. Adjusted to the following error goes away
![image](https://user-images.githubusercontent.com/22269729/147834851-0239bba3-14bc-44f3-9de0-950b60a28947.png)

But `F5` will see the highlighted debug toolbar disappear after a few seconds yet it's still running and won't stop at breakpoint line 6.
![image](https://user-images.githubusercontent.com/22269729/147834969-db90c6b4-1b6d-40a9-b9a5-2ceb6d716422.png)

**UPDATE**, F5 debug toolbar stays after adding and run this this new config into `.vscode\launch.json`, still not able to stop at breakpoint.
```
{
          "name": "Launch Program",
          "preLaunchTask": "func: host start",
          "program": "${workspaceFolder}/azapp/app.js",
          "request": "launch",
          "skipFiles": [
              "<node_internals>/**"
          ],
          "type": "pwa-node"
      },
```
